import p1_img from "./male1.png";
import p2_img from "./female4.png";
import p3_img from "./male6.png";
import p4_img from "./female3.png";
let relatedF = [
  {
    id: 1,
    name: "The'Zaid' Forest green Minimalist Senator Set",
    category: "Men",
    description:"Elevate your formal style with this premuim forest senator suit,a contemporary take on a traditional design.",
    image: p1_img,
    new_price: 25000.0,
    old_price: 80.5,
  },
  {
    id: 8,
    name: "The Dark Green two peice wear",
    category: "Women",
    image: p2_img,
    description:"This contemporary ensamble features a high-waisted, wide-leg trouser paired with a matching short-sleeved button-down shirt.",
    new_price: 24500.0,
    old_price: 120.5,
  },
  {
    id: 11,
    name: "The Majestic Lion Tee",
    category: "Men",
    image: p3_img,
    description:"This statement peice features the bold,high difination graphic print of a lion's face,symbolizing strength and leadership.",
    new_price: 25000.0,
    old_price: 120.5,
  },
  {
    id: 6,
    name: "The Fitted Ankara Gown",
    category: "Women",
    image: p4_img,
    description:"this is a modenised traditional ankara gownn which emits a radiance of beauty in a modernised way.",
    new_price: 24500.0,
    old_price: 120.5,
  },
];

export default relatedF;
